# Generated by Django 2.2.1 on 2020-01-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
