# Generated by Django 2.2.1 on 2020-01-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_page_page_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shuugch',
            name='image',
            field=models.FileField(default=1, upload_to='page_img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shuugch',
            name='tuhai',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
