# Generated by Django 2.2.1 on 2020-01-23 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='team_member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=200)),
                ('register_number', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='member_img')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='competitions.team')),
            ],
        ),
    ]
