# Generated by Django 2.2.1 on 2020-01-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_team_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('torol', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('ovog', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('ognoo', models.DateField()),
                ('register_number', models.CharField(max_length=200)),
                ('irgenii_haryalal', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone_home', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('social', models.CharField(max_length=200)),
                ('nasnii_angilal', models.CharField(max_length=200)),
                ('bujgiin_ner_1', models.CharField(max_length=200)),
                ('bujgiin_ner_2', models.CharField(max_length=200)),
                ('hugatsaa_1', models.CharField(max_length=200)),
                ('hugatsaa_2', models.CharField(max_length=200)),
                ('teacher', models.CharField(max_length=200)),
                ('teacher_ovog', models.CharField(max_length=200)),
                ('school', models.CharField(max_length=200)),
                ('hicheellesen_hugatsaa', models.CharField(max_length=200)),
                ('teacher_phone', models.IntegerField()),
                ('teacher_email', models.CharField(max_length=50)),
                ('teacher_social', models.CharField(max_length=50)),
            ],
        ),
    ]
