# Generated by Django 2.2.1 on 2020-01-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
