# Generated by Django 2.2.1 on 2020-01-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0011_team_hicheelelsen_hugatsaa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_member',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='member_img'),
        ),
    ]
